CREATE DATABASE IF NOT EXISTS admin_accounts;
USE admin_accounts;

CREATE TABLE IF NOT EXISTS admin_accounts (
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) PRIMARY KEY,
  PASSWORD VARCHAR(255) NOT NULL
);